version: '3.8'
services:
  db:
    image: mysql:8.0.13
    container_name: cmsxeramed_db
    environment:
      MYSQL_ROOT_PASSWORD: Xeranor6234!
      MYSQL_DATABASE: cmsxeramed_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    image: cmsxeramed-backend:1.0
    container_name: cmsxeramed-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
